#### general settings
name: PointHet
train_type: gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  dataset: "BRCA"
  wsi_path: "./data/BRCA/testing/images"
  task: "cancer staging"
  train_path: "./data/BRCA_kimia_lv0/list_staging_f1/heterogeneous_train.txt"
  eval_path: "./data/BRCA_kimia_lv0/list_staging_f1/heterogeneous_test.txt"
  valid_path: "./data/BRCA_kimia_lv0/list_staging/heterogeneous_val.txt"
  normal_path: "./data/clinical_data/staging_BRCA.txt"
  has_graph: True
  num_workers: 16

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/HEAT3_BRCA_Kimia_lv0_staging_f1"
  save_checkpoint_freq: 5

#### Patches extractor settings
selector:

  n_channel: 3
  pixel_th: 200

  level: 5
  patch_size: 256
  verbose: 0

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.00005 # Learning rate
  weight_decay: 0.005

#### GNN settings
GNN:
  name: "HEAT3"

  n_node_types: 6

  num_meta_paths: 3
  num_layers: 2
  in_dim: 1024
  hidden_dim: 256
  out_dim: 4
  n_heads: 4
  num_out_heads: 1
  feat_drop: 0

  graph_pooling_type: mean

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 500
  batch_size: 1

  loss: "CE"

eval:
  explainer_name: GemExplainer
  explain_path: "./plots/HEAT_COADv2_full_Kimia_lv0_expl_typing/"