graph_constructor:
  dataset: COAD

  encoder_name: 'efficientnet-b7'  # efficientnet-b7 / kimia / hover

  data_root: "./data/COAD/"
  hovernet_data_root: "./data/hovernet_json"
  out_dir: "./data/COAD_Eff_lv2"

  patch_size: 256
  feature_dim: 1024
  radius: 9
  level: 2
  n_channel: 3
  n_node_type: 6
  verbose: 0

hovernet_config:
  nr_types: 6
  mode: fast
  hovernet_model_path: './data/weights/hovernet_fast_pannuke_type_tf2pytorch.tar'
  type_info_path: 'type_info.json'
  batch_size: 16

kimianet_config:
  kimianet_model_path: './data/weights/KimiaNetPyTorchWeights.pth'
  batch_size: 16