batch_size: 64
epochs: 20
eval_every_n_epochs: 1
fine_tune_from: 'kimianet'
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: True
n_gpu: 1
gpu_ids: '0'

model:
  out_dim: 1024
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (256,256,3)
  num_workers: 4
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True
