#### general settings
name: PointHet
train_type: point-het
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  dataset: "COAD"
  wsi_path: "./data/COAD/"
  train_path: "./data/COADv2_hover_lv0/list/homogeneous_train.txt"
  eval_path: "./data/COADv2_hover_lv0/list/homogeneous_test.txt"
  normal_path: "./data/biomedical_data/normal_list.txt"
  has_graph: True
  num_workers: 16

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/AdaGCN_COADv2_Hover/"
  save_checkpoint_freq: 10

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.00001  # Learning rate
  weight_decay: 0.001

#### Patches extractor settings
selector:

  n_channel: 3
  pixel_th: 200

  level: 5
  patch_size: 256
  verbose: 0

#### GNN settings
GNN:
    name: "AdaGCN"

    num_layers: 2
    in_dim: 1024
    hidden_dim: 64
    out_dim: 2
    ratio: 0.4
    dropout_att: 0.1

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 200
  batch_size: 1

  loss: "CE"

#### evaluation settings: learning rate scheme, loss, optimizer
eval:
  explain_path: "./plots/AdaGCN_COAD_HoverKimia_expl/"