#### general settings
name: PointHet
train_type: gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  dataset: "COAD"
  wsi_path: "./data/COAD/"
  task: "cancer classification"
  train_path: "./data/COAD_kimia_lv0/list/heterogeneous_train.txt"
  eval_path: "./data/COAD_kimia_lv0/list/heterogeneous_test.txt"
  valid_path: "./data/COAD_kimia_lv0/list/heterogeneous_val.txt"
  normal_path: "./data/biomedical_data/normal_list.txt"
  has_graph: True
  num_workers: 16

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/HetRGCN_COADv2_full_Kimia/"
  save_checkpoint_freq: 5

#### Patches extractor settings
selector:

  n_channel: 3
  pixel_th: 200

  level: 2
  patch_size: 256
  verbose: 0

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005  # Learning rate
  weight_decay: 0.001


#### GNN settings
GNN:
  name: "HetRGCN"

  n_node_types: 6
  edge_types: ["pos", "neg"]
  num_meta_paths: 3
  num_layers: 2
  in_dim: 1024
  hidden_dim: 200
  out_dim: 2
  feat_drop: 0.2

  graph_pooling_type: mean

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 400
  batch_size: 1

  loss: "CE"

eval:
  explain_path: "./plots/HetRGCN_COAD_Hover_expl/"