#### general settings
name: PointHet
train_type: gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  dataset: "COAD"
  wsi_path: "./data/COAD/testing/images"
  task: "cancer staging"
  train_path: "./data/COAD_kimia_lv0/list_staging/heterogeneous_train.txt"
  eval_path: "./data/COAD_kimia_lv0/list_staging/heterogeneous_test.txt"
  valid_path: "./data/COAD_kimia_lv0/list_staging/heterogeneous_val.txt"
  normal_path: "./data/clinical_data/staging.txt"
  has_graph: True
  num_workers: 16

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/HGT_COAD_full_Kimia_staging"
  save_checkpoint_freq: 5

#### Patches extractor settings
selector:

  n_channel: 3
  pixel_th: 200

  level: 5
  patch_size: 256
  verbose: 0

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001 # Learning rate
  weight_decay: 0.001

#### GNN settings
#### GNN settings
GNN:
  name: "HGT"

  n_node_types: 6
  edge_types: ["pos", "neg"]
  num_meta_paths: 3
  num_layers: 2
  in_dim: 1024
  hidden_dim: 200
  out_dim: 4
  num_heads: 4
  num_out_heads: 1
  feat_drop: 0.4

  graph_pooling_type: mean

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 500
  batch_size: 1

  loss: "CE"

eval:
  explainer_name: GemExplainer
  explain_path: "./plots/HGT_COADv2_full_Kimia_lv0_expl_typing/"